import type { PseSector } from "../types";

export interface PseEdgeCompany {
  /** Ticker symbol exactly as PSE Edge lists it. */
  ticker: string;
  /** PSE Edge's internal company id — the `cmpy_id` query param `stockData.do` takes. */
  cmpyId: string;
  companyName: string;
  sector: PseSector;
}

/**
 * Full ticker -> PSE Edge cmpy_id roster: every one of the 282 companies listed in
 * PSE Edge's public Company Directory (`/companyDirectory/search.ax`), the
 * authoritative source for symbol, cmpy_id, and sector. Regenerate when PSE
 * lists/delists/renames a security by POSTing to that endpoint once per page
 * (pageNo=1..N, sector=ALL, subsector=ALL) — each row's onclick
 * `cmDetail('<cmpyId>','<securityId>')` yields the cmpy_id, and the row's tds
 * give symbol, sector, and subsector.
 *
 * Sector strings are PSE Edge's own labels, normalized: "Mining and Oil" ->
 * "Mining & Oil", "Small, Medium & Emerging Board" -> "SME Board". Everything
 * keying off this roster (quotes, historical, disclosures, corporate actions)
 * matches by cmpy_id, so a symbol change alone never breaks the join.
 */
export const PSE_EDGE_COMPANIES: readonly PseEdgeCompany[] = [
  // Financials
  { ticker: "AUB", cmpyId: "641", companyName: "Asia United Bank Corporation", sector: "Financials" },
  { ticker: "BDO", cmpyId: "260", companyName: "BDO Unibank, Inc.", sector: "Financials" },
  { ticker: "BKR", cmpyId: "66", companyName: "Bright Kindle Resources & Investments Inc.", sector: "Financials" },
  { ticker: "BNCOM", cmpyId: "692", companyName: "Bank of Commerce", sector: "Financials" },
  { ticker: "BPI", cmpyId: "234", companyName: "Bank of the Philippine Islands", sector: "Financials" },
  { ticker: "CBC", cmpyId: "184", companyName: "China Banking Corporation", sector: "Financials" },
  { ticker: "COL", cmpyId: "601", companyName: "COL Financial Group, Inc.", sector: "Financials" },
  { ticker: "CSB", cmpyId: "228", companyName: "Citystate Savings Bank, Inc.", sector: "Financials" },
  { ticker: "DHI", cmpyId: "31", companyName: "Dominion Holdings, Inc.", sector: "Financials" },
  { ticker: "EW", cmpyId: "634", companyName: "East West Banking Corporation", sector: "Financials" },
  { ticker: "FAF", cmpyId: "81", companyName: "First Abacus Financial Holdings Corporation", sector: "Financials" },
  { ticker: "FERRO", cmpyId: "643", companyName: "Ferronoux Holdings, Inc.", sector: "Financials" },
  { ticker: "FFI", cmpyId: "196", companyName: "Filipino Fund, Inc.", sector: "Financials" },
  { ticker: "I", cmpyId: "613", companyName: "I-Remit, Inc.", sector: "Financials" },
  { ticker: "LMG", cmpyId: "205", companyName: "LMG Corp.", sector: "Financials" },
  { ticker: "MBT", cmpyId: "128", companyName: "Metropolitan Bank & Trust Company", sector: "Financials" },
  { ticker: "MED", cmpyId: "126", companyName: "MEDCO Holdings, Inc.", sector: "Financials" },
  { ticker: "MFC", cmpyId: "120", companyName: "Manulife Financial Corporation", sector: "Financials" },
  { ticker: "NRCP", cmpyId: "606", companyName: "National Reinsurance Corporation of the Philippines", sector: "Financials" },
  { ticker: "NXGEN", cmpyId: "179", companyName: "NextGenesis Corporation", sector: "Financials" },
  { ticker: "PBB", cmpyId: "640", companyName: "Philippine Business Bank", sector: "Financials" },
  { ticker: "PBC", cmpyId: "208", companyName: "Philippine Bank of Communications", sector: "Financials" },
  { ticker: "PNB", cmpyId: "139", companyName: "Philippine National Bank", sector: "Financials" },
  { ticker: "PSB", cmpyId: "142", companyName: "Philippine Savings Bank", sector: "Financials" },
  { ticker: "PSE", cmpyId: "478", companyName: "The Philippine Stock Exchange, Inc.", sector: "Financials" },
  { ticker: "PTC", cmpyId: "144", companyName: "Philippine Trust Company", sector: "Financials" },
  { ticker: "RCB", cmpyId: "232", companyName: "Rizal Commercial Banking Corporation", sector: "Financials" },
  { ticker: "SECB", cmpyId: "32", companyName: "Security Bank Corporation", sector: "Financials" },
  { ticker: "SLF", cmpyId: "78", companyName: "Sun Life Financial Inc.", sector: "Financials" },
  { ticker: "UBP", cmpyId: "167", companyName: "Union Bank of the Philippines", sector: "Financials" },
  { ticker: "V", cmpyId: "65", companyName: "Vantage Equities, Inc.", sector: "Financials" },

  // Industrial
  { ticker: "ACEN", cmpyId: "233", companyName: "ACEN CORPORATION", sector: "Industrial" },
  { ticker: "ACR", cmpyId: "121", companyName: "Alsons Consolidated Resources, Inc.", sector: "Industrial" },
  { ticker: "ALTER", cmpyId: "701", companyName: "Alternergy Holdings Corporation", sector: "Industrial" },
  { ticker: "ANI", cmpyId: "619", companyName: "AgriNurture, Inc.", sector: "Industrial" },
  { ticker: "AP", cmpyId: "609", companyName: "Aboitiz Power Corporation", sector: "Industrial" },
  { ticker: "ASLAG", cmpyId: "694", companyName: "Raslag Corp.", sector: "Industrial" },
  { ticker: "ATN", cmpyId: "56", companyName: "ATN Holdings, Inc.", sector: "Industrial" },
  { ticker: "AXLM", cmpyId: "673", companyName: "Axelum Resources Corp.", sector: "Industrial" },
  { ticker: "BALAI", cmpyId: "697", companyName: "Balai Ni Fruitas Inc.", sector: "Industrial" },
  { ticker: "BMM", cmpyId: "181", companyName: "Bogo-Medellin Milling Company, Inc.", sector: "Industrial" },
  { ticker: "BSC", cmpyId: "60", companyName: "Basic Energy Corporation", sector: "Industrial" },
  { ticker: "CA", cmpyId: "213", companyName: "Concrete Aggregates Corporation", sector: "Industrial" },
  { ticker: "CAT", cmpyId: "183", companyName: "Central Azucarera de Tarlac, Inc.", sector: "Industrial" },
  { ticker: "CHP", cmpyId: "662", companyName: "Concreat Holdings Philippines, Inc.", sector: "Industrial" },
  { ticker: "CIC", cmpyId: "648", companyName: "Concepcion Industrial Corporation", sector: "Industrial" },
  { ticker: "CNPF", cmpyId: "652", companyName: "Century Pacific Food, Inc.", sector: "Industrial" },
  { ticker: "CREC", cmpyId: "703", companyName: "Citicore Renewable Energy Corporation", sector: "Industrial" },
  { ticker: "CROWN", cmpyId: "657", companyName: "Crown Asia Chemicals Corporation", sector: "Industrial" },
  { ticker: "DELM", cmpyId: "642", companyName: "Del Monte Pacific Limited", sector: "Industrial" },
  { ticker: "DNL", cmpyId: "639", companyName: "D&L Industries, Inc.", sector: "Industrial" },
  { ticker: "EEI", cmpyId: "71", companyName: "EEI Corporation", sector: "Industrial" },
  { ticker: "EMI", cmpyId: "632", companyName: "Emperador Inc.", sector: "Industrial" },
  { ticker: "EURO", cmpyId: "219", companyName: "Euro-Med Laboratories Phil., Inc.", sector: "Industrial" },
  { ticker: "FB", cmpyId: "151", companyName: "San Miguel Food and Beverage, Inc.", sector: "Industrial" },
  { ticker: "FCG", cmpyId: "689", companyName: "Figaro Culinary Group, Inc.", sector: "Industrial" },
  { ticker: "FGEN", cmpyId: "600", companyName: "First Gen Corporation", sector: "Industrial" },
  { ticker: "FOOD", cmpyId: "602", companyName: "Alliance Select Foods International, Inc.", sector: "Industrial" },
  { ticker: "FPH", cmpyId: "197", companyName: "First Philippine Holdings Corporation", sector: "Industrial" },
  { ticker: "FRUIT", cmpyId: "676", companyName: "Fruitas Holdings, Inc.", sector: "Industrial" },
  { ticker: "FYN", cmpyId: "80", companyName: "Filsyn Corporation", sector: "Industrial" },
  { ticker: "GREEN", cmpyId: "132", companyName: "Greenergy Holdings Incorporated", sector: "Industrial" },
  { ticker: "GSMI", cmpyId: "94", companyName: "Ginebra San Miguel,  Inc.", sector: "Industrial" },
  { ticker: "IMI", cmpyId: "622", companyName: "Integrated Micro-Electronics, Inc.", sector: "Industrial" },
  { ticker: "ION", cmpyId: "203", companyName: "Ionics, Inc.", sector: "Industrial" },
  { ticker: "JFC", cmpyId: "86", companyName: "Jollibee Foods Corporation", sector: "Industrial" },
  { ticker: "JOH", cmpyId: "261", companyName: "Jolliville Holdings Corporation", sector: "Industrial" },
  { ticker: "KEEPR", cmpyId: "2", companyName: "The Keepers Holdings, Inc.", sector: "Industrial" },
  { ticker: "LFM", cmpyId: "227", companyName: "Liberty Flour Mills, Inc.", sector: "Industrial" },
  { ticker: "MACAY", cmpyId: "145", companyName: "Macay Holdings, Inc.", sector: "Industrial" },
  { ticker: "MAXS", cmpyId: "135", companyName: "Max's Group, Inc.", sector: "Industrial" },
  { ticker: "MER", cmpyId: "118", companyName: "Manila Electric Company", sector: "Industrial" },
  { ticker: "MG", cmpyId: "105", companyName: "Millennium Global Holdings, Inc.", sector: "Industrial" },
  { ticker: "MONDE", cmpyId: "682", companyName: "Monde Nissin Corporation", sector: "Industrial" },
  { ticker: "MVC", cmpyId: "100", companyName: "Mabuhay Vinyl Corporation", sector: "Industrial" },
  { ticker: "MWC", cmpyId: "270", companyName: "Manila Water Company, Inc.", sector: "Industrial" },
  { ticker: "MWIDE", cmpyId: "627", companyName: "Megawide Construction Corporation", sector: "Industrial" },
  { ticker: "MYNLD", cmpyId: "707", companyName: "Maynilad Water Services, Inc.", sector: "Industrial" },
  { ticker: "PCOR", cmpyId: "136", companyName: "Petron Corporation", sector: "Industrial" },
  { ticker: "PERC", cmpyId: "578", companyName: "PetroEnergy Resources Corporation", sector: "Industrial" },
  { ticker: "PHN", cmpyId: "107", companyName: "Phinma Corporation", sector: "Industrial" },
  { ticker: "PIZZA", cmpyId: "664", companyName: "Shakey's Pizza Asia Ventures, Inc.", sector: "Industrial" },
  { ticker: "PMPC", cmpyId: "104", companyName: "Panasonic Manufacturing Philippines Corporation", sector: "Industrial" },
  { ticker: "PNC", cmpyId: "7", companyName: "Philippine National Construction Corporation", sector: "Industrial" },
  { ticker: "PNX", cmpyId: "608", companyName: "Phoenix Petroleum Philippines, Inc.", sector: "Industrial" },
  { ticker: "PPC", cmpyId: "150", companyName: "Pryce Corporation", sector: "Industrial" },
  { ticker: "RCI", cmpyId: "54", companyName: "Roxas and Company, Inc.", sector: "Industrial" },
  { ticker: "REDC", cmpyId: "702", companyName: "Repower Energy Development Corporation", sector: "Industrial" },
  { ticker: "RFM", cmpyId: "77", companyName: "RFM Corporation", sector: "Industrial" },
  { ticker: "ROX", cmpyId: "64", companyName: "Roxas Holdings,  Inc.", sector: "Industrial" },
  { ticker: "SCC", cmpyId: "157", companyName: "Semirara Mining and Power Corporation", sector: "Industrial" },
  { ticker: "SFI", cmpyId: "165", companyName: "Swift Foods, Inc.", sector: "Industrial" },
  { ticker: "SGP", cmpyId: "166", companyName: "Synergy Grid & Development Phils., Inc.", sector: "Industrial" },
  { ticker: "SHLPH", cmpyId: "663", companyName: "Shell Pilipinas Corporation", sector: "Industrial" },
  { ticker: "SPC", cmpyId: "237", companyName: "SPC Power Corporation", sector: "Industrial" },
  { ticker: "SPNEC", cmpyId: "688", companyName: "SP New Energy Corporation", sector: "Industrial" },
  { ticker: "SRDC", cmpyId: "479", companyName: "Supercity Realty Development Corporation", sector: "Industrial" },
  { ticker: "STN", cmpyId: "164", companyName: "Steniel Manufacturing Corporation", sector: "Industrial" },
  { ticker: "T", cmpyId: "163", companyName: "TKC Metals Corporation", sector: "Industrial" },
  { ticker: "TECH", cmpyId: "630", companyName: "Cirtek Holdings Philippines Corporation", sector: "Industrial" },
  { ticker: "TOP", cmpyId: "706", companyName: "Top Line Business Development Corp.", sector: "Industrial" },
  { ticker: "URC", cmpyId: "124", companyName: "Universal Robina Corporation", sector: "Industrial" },
  { ticker: "VITA", cmpyId: "28", companyName: "Vitarich Corporation", sector: "Industrial" },
  { ticker: "VMC", cmpyId: "123", companyName: "Victorias Milling Company, Inc.", sector: "Industrial" },
  { ticker: "VVT", cmpyId: "79", companyName: "Vivant Corporation", sector: "Industrial" },

  // Holding Firms
  { ticker: "AAA", cmpyId: "55", companyName: "Asia Amalgamated Holdings Corporation", sector: "Holding Firms" },
  { ticker: "ABA", cmpyId: "174", companyName: "AbaCore Capital Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "ABG", cmpyId: "176", companyName: "Asiabest Group International Inc.", sector: "Holding Firms" },
  { ticker: "AC", cmpyId: "57", companyName: "Ayala Corporation", sector: "Holding Firms" },
  { ticker: "AEV", cmpyId: "16", companyName: "Aboitiz Equity Ventures, Inc.", sector: "Holding Firms" },
  { ticker: "AGI", cmpyId: "212", companyName: "Alliance Global Group, Inc.", sector: "Holding Firms" },
  { ticker: "ANS", cmpyId: "14", companyName: "A. Soriano Corporation", sector: "Holding Firms" },
  { ticker: "APO", cmpyId: "52", companyName: "Anglo Philippine Holdings Corporation", sector: "Holding Firms" },
  { ticker: "BH", cmpyId: "62", companyName: "BHI Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "COSCO", cmpyId: "50", companyName: "Cosco Capital, Inc.", sector: "Holding Firms" },
  { ticker: "DMC", cmpyId: "188", companyName: "DMCI Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "FDC", cmpyId: "75", companyName: "Filinvest Development Corporation", sector: "Holding Firms" },
  { ticker: "FJP", cmpyId: "225", companyName: "F & J Prince Holdings Corporation", sector: "Holding Firms" },
  { ticker: "FPI", cmpyId: "220", companyName: "Forum Pacific, Inc.", sector: "Holding Firms" },
  { ticker: "GTCAP", cmpyId: "633", companyName: "GT Capital Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "HI", cmpyId: "82", companyName: "House of Investments, Inc.", sector: "Holding Firms" },
  { ticker: "JGS", cmpyId: "210", companyName: "JG Summit Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "LODE", cmpyId: "37", companyName: "Lodestar Investment Holdings Corporation", sector: "Holding Firms" },
  { ticker: "LPZ", cmpyId: "61", companyName: "Lopez Holdings Corporation", sector: "Holding Firms" },
  { ticker: "LTG", cmpyId: "12", companyName: "LT Group, Inc.", sector: "Holding Firms" },
  { ticker: "MGH", cmpyId: "192", companyName: "Metro Global Holdings Corporation", sector: "Holding Firms" },
  { ticker: "MHC", cmpyId: "206", companyName: "Mabuhay Holdings Corporation", sector: "Holding Firms" },
  { ticker: "PA", cmpyId: "109", companyName: "Pacifica Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "PRIM", cmpyId: "30", companyName: "Prime Media Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "REG", cmpyId: "153", companyName: "Republic Glass Holdings Corporation", sector: "Holding Firms" },
  { ticker: "SGI", cmpyId: "160", companyName: "Solid Group, Inc.", sector: "Holding Firms" },
  { ticker: "SM", cmpyId: "599", companyName: "SM Investments Corporation", sector: "Holding Firms" },
  { ticker: "SMC", cmpyId: "154", companyName: "San Miguel Corporation", sector: "Holding Firms" },
  { ticker: "SPM", cmpyId: "156", companyName: "Seafront Resources Corporation", sector: "Holding Firms" },
  { ticker: "TFHI", cmpyId: "650", companyName: "Top Frontier Investment Holdings, Inc.", sector: "Holding Firms" },
  { ticker: "ZHI", cmpyId: "89", companyName: "Zeus Holdings, Inc.", sector: "Holding Firms" },

  // Property
  { ticker: "ALCO", cmpyId: "172", companyName: "Arthaland Corporation", sector: "Property" },
  { ticker: "ALHI", cmpyId: "612", companyName: "Anchor Land Holdings, Inc.", sector: "Property" },
  { ticker: "ALI", cmpyId: "180", companyName: "Ayala Land, Inc.", sector: "Property" },
  { ticker: "ALLHC", cmpyId: "26", companyName: "AyalaLand Logistics Holdings Corp.", sector: "Property" },
  { ticker: "APVI", cmpyId: "678", companyName: "Altus Property Ventures, Inc.", sector: "Property" },
  { ticker: "ARA", cmpyId: "38", companyName: "Araneta Properties, Inc.", sector: "Property" },
  { ticker: "AREIT", cmpyId: "679", companyName: "AREIT, Inc.", sector: "Property" },
  { ticker: "BRN", cmpyId: "13", companyName: "A Brown Company, Inc.", sector: "Property" },
  { ticker: "CDC", cmpyId: "39", companyName: "Cityland Development Corporation", sector: "Property" },
  { ticker: "CEI", cmpyId: "186", companyName: "Crown Equities, Inc.", sector: "Property" },
  { ticker: "CLI", cmpyId: "668", companyName: "Cebu Landmasters, Inc.", sector: "Property" },
  { ticker: "CPG", cmpyId: "189", companyName: "Century Properties Group, Inc.", sector: "Property" },
  { ticker: "CREIT", cmpyId: "691", companyName: "Citicore Energy REIT Corp.", sector: "Property" },
  { ticker: "CYBR", cmpyId: "67", companyName: "Cyber Bay Corporation", sector: "Property" },
  { ticker: "DD", cmpyId: "651", companyName: "DoubleDragon Corporation", sector: "Property" },
  { ticker: "DDMPR", cmpyId: "681", companyName: "DDMP REIT, Inc.", sector: "Property" },
  { ticker: "DMW", cmpyId: "671", companyName: "D.M. Wenceslao & Associates, Incorporated", sector: "Property" },
  { ticker: "EGRN", cmpyId: "191", companyName: "Everwoods Green Resources and Holdings, Inc.", sector: "Property" },
  { ticker: "ELI", cmpyId: "190", companyName: "Empire East Land Holdings, Inc.", sector: "Property" },
  { ticker: "FILRT", cmpyId: "683", companyName: "Filinvest REIT Corp.", sector: "Property" },
  { ticker: "FLI", cmpyId: "226", companyName: "Filinvest Land, Inc.", sector: "Property" },
  { ticker: "GERI", cmpyId: "193", companyName: "Global-Estate Resorts, Inc.", sector: "Property" },
  { ticker: "INFRA", cmpyId: "84", companyName: "Philippine Infradev Holdings, Inc.", sector: "Property" },
  { ticker: "JAS", cmpyId: "134", companyName: "Jackstones, Inc.", sector: "Property" },
  { ticker: "KEP", cmpyId: "88", companyName: "Keppel Philippines Properties, Inc.", sector: "Property" },
  { ticker: "MEG", cmpyId: "127", companyName: "Megaworld Corporation", sector: "Property" },
  { ticker: "MRC", cmpyId: "131", companyName: "MRC Allied, Inc.", sector: "Property" },
  { ticker: "MREIT", cmpyId: "685", companyName: "MREIT, Inc.", sector: "Property" },
  { ticker: "OM", cmpyId: "207", companyName: "Omico Corporation", sector: "Property" },
  { ticker: "PHA", cmpyId: "148", companyName: "Premiere Horizon Alliance Corporation", sector: "Property" },
  { ticker: "PHES", cmpyId: "138", companyName: "Philippine Estates Corporation", sector: "Property" },
  { ticker: "PRC", cmpyId: "141", companyName: "Philippine Racing Club, Inc.", sector: "Property" },
  { ticker: "PREIT", cmpyId: "699", companyName: "Premiere Island Power REIT Corporation", sector: "Property" },
  { ticker: "PRMX", cmpyId: "214", companyName: "Primex Corporation", sector: "Property" },
  { ticker: "RCR", cmpyId: "684", companyName: "RL Commercial REIT, Inc.", sector: "Property" },
  { ticker: "RLC", cmpyId: "195", companyName: "Robinsons Land Corporation", sector: "Property" },
  { ticker: "RLT", cmpyId: "40", companyName: "Philippine Realty and Holdings Corporation", sector: "Property" },
  { ticker: "ROCK", cmpyId: "635", companyName: "Rockwell Land Corporation", sector: "Property" },
  { ticker: "SHNG", cmpyId: "218", companyName: "Shang Properties, Inc.", sector: "Property" },
  { ticker: "SLI", cmpyId: "41", companyName: "Sta. Lucia Land, Inc.", sector: "Property" },
  { ticker: "SMPH", cmpyId: "112", companyName: "SM Prime Holdings, Inc.", sector: "Property" },
  { ticker: "SOC", cmpyId: "161", companyName: "SOCResources, Inc.", sector: "Property" },
  { ticker: "STR", cmpyId: "147", companyName: "Vistamalls, Inc.", sector: "Property" },
  { ticker: "SUN", cmpyId: "73", companyName: "Suntrust Resort Holdings, Inc.", sector: "Property" },
  { ticker: "TFC", cmpyId: "8", companyName: "PTFC Redevelopment Corporation", sector: "Property" },
  { ticker: "UNH", cmpyId: "22", companyName: "Uniholdings Inc.", sector: "Property" },
  { ticker: "VLC", cmpyId: "661", companyName: "Villar Land Holdings Corp.", sector: "Property" },
  { ticker: "VLL", cmpyId: "607", companyName: "Vista Land & Lifescapes, Inc.", sector: "Property" },
  { ticker: "VREIT", cmpyId: "695", companyName: "VistaREIT, Inc.", sector: "Property" },
  { ticker: "WIN", cmpyId: "90", companyName: "Wellex Industries, Incorporated", sector: "Property" },

  // Services
  { ticker: "ABS", cmpyId: "114", companyName: "ABS-CBN Corporation", sector: "Services" },
  { ticker: "ABSP", cmpyId: "15", companyName: "ABS-CBN Holdings Corporation", sector: "Services" },
  { ticker: "ACE", cmpyId: "48", companyName: "Acesite (Phils.) Hotel Corporation", sector: "Services" },
  { ticker: "ALLDY", cmpyId: "686", companyName: "AllDay Marts, Inc.", sector: "Services" },
  { ticker: "APC", cmpyId: "177", companyName: "APC Group, Inc.", sector: "Services" },
  { ticker: "APL", cmpyId: "638", companyName: "Apollo Global Capital, Inc.", sector: "Services" },
  { ticker: "BCOR", cmpyId: "9", companyName: "Berjaya Philippines Inc.", sector: "Services" },
  { ticker: "BEL", cmpyId: "21", companyName: "Belle Corporation", sector: "Services" },
  { ticker: "BHI", cmpyId: "63", companyName: "Boulevard Holdings, Inc.", sector: "Services" },
  { ticker: "BLOOM", cmpyId: "49", companyName: "Bloomberry Resorts Corporation", sector: "Services" },
  { ticker: "C", cmpyId: "669", companyName: "Chelsea Logistics and Infrastructure Holdings Corp.", sector: "Services" },
  { ticker: "CEB", cmpyId: "624", companyName: "Cebu Air, Inc.", sector: "Services" },
  { ticker: "CEU", cmpyId: "223", companyName: "Centro Escolar University", sector: "Services" },
  { ticker: "CNVRG", cmpyId: "680", companyName: "Converge Information and Communications Technology Solutions, Inc.", sector: "Services" },
  { ticker: "DFNN", cmpyId: "187", companyName: "DFNN, Inc.", sector: "Services" },
  { ticker: "DITO", cmpyId: "36", companyName: "DITO CME Holdings Corp.", sector: "Services" },
  { ticker: "DWC", cmpyId: "647", companyName: "Discovery World Corporation", sector: "Services" },
  { ticker: "ECP", cmpyId: "70", companyName: "EasyCall Communications Philippines, Inc.", sector: "Services" },
  { ticker: "EG", cmpyId: "623", companyName: "IP E-Game Ventures, Inc.", sector: "Services" },
  { ticker: "FEU", cmpyId: "25", companyName: "Far Eastern University, Incorporated", sector: "Services" },
  { ticker: "GLO", cmpyId: "69", companyName: "Globe Telecom, Inc.", sector: "Services" },
  { ticker: "GMA7", cmpyId: "610", companyName: "GMA Network, Inc.", sector: "Services" },
  { ticker: "GMAP", cmpyId: "611", companyName: "GMA Holdings, Inc.", sector: "Services" },
  { ticker: "GPH", cmpyId: "221", companyName: "Grand Plaza Hotel Corporation", sector: "Services" },
  { ticker: "HOME", cmpyId: "674", companyName: "AllHome Corp.", sector: "Services" },
  { ticker: "ICT", cmpyId: "83", companyName: "International Container Terminal Services, Inc.", sector: "Services" },
  { ticker: "IMP", cmpyId: "201", companyName: "Imperial Resources, Inc.", sector: "Services" },
  { ticker: "IPM", cmpyId: "4", companyName: "IPM Holdings, Inc.", sector: "Services" },
  { ticker: "IPO", cmpyId: "85", companyName: "iPeople, inc.", sector: "Services" },
  { ticker: "IS", cmpyId: "204", companyName: "Island Information & Technology, Inc.", sector: "Services" },
  { ticker: "LBC", cmpyId: "236", companyName: "LBC Express Holdings, Inc.", sector: "Services" },
  { ticker: "LOTO", cmpyId: "605", companyName: "Pacific Online Systems Corporation", sector: "Services" },
  { ticker: "LSC", cmpyId: "115", companyName: "Lorenzo Shipping Corporation", sector: "Services" },
  { ticker: "MAC", cmpyId: "106", companyName: "MacroAsia Corporation", sector: "Services" },
  { ticker: "MAH", cmpyId: "3", companyName: "Metro Alliance Holdings & Equities Corp.", sector: "Services" },
  { ticker: "MB", cmpyId: "1", companyName: "Manila Bulletin Publishing Corporation", sector: "Services" },
  { ticker: "MBC", cmpyId: "117", companyName: "Manila Broadcasting Company", sector: "Services" },
  { ticker: "MEDIC", cmpyId: "687", companyName: "Medilines Distributors Incorporated", sector: "Services" },
  { ticker: "MJC", cmpyId: "102", companyName: "Manila Jockey Club, Inc.", sector: "Services" },
  { ticker: "MJIC", cmpyId: "24", companyName: "MJC Investments Corporation", sector: "Services" },
  { ticker: "MRSGI", cmpyId: "659", companyName: "Metro Retail Stores Group, Inc.", sector: "Services" },
  { ticker: "NOW", cmpyId: "264", companyName: "Now Corporation", sector: "Services" },
  { ticker: "PAL", cmpyId: "20", companyName: "PAL Holdings, Inc.", sector: "Services" },
  { ticker: "PAX", cmpyId: "194", companyName: "Paxys, Inc.", sector: "Services" },
  { ticker: "PGOLD", cmpyId: "629", companyName: "Puregold Price Club, Inc.", sector: "Services" },
  { ticker: "PHC", cmpyId: "97", companyName: "Philcomsat Holdings Corporation", sector: "Services" },
  { ticker: "PHR", cmpyId: "631", companyName: "PH Resorts Group Holdings, Inc.", sector: "Services" },
  { ticker: "PLUS", cmpyId: "96", companyName: "DigiPlus Interactive Corp.", sector: "Services" },
  { ticker: "PORT", cmpyId: "129", companyName: "Globalport 900, Inc.", sector: "Services" },
  { ticker: "PTT", cmpyId: "76", companyName: "PT&T Corp.", sector: "Services" },
  { ticker: "RRHI", cmpyId: "646", companyName: "Robinsons Retail Holdings, Inc.", sector: "Services" },
  { ticker: "SBS", cmpyId: "658", companyName: "SBS Philippines Corporation", sector: "Services" },
  { ticker: "SEVN", cmpyId: "143", companyName: "Philippine Seven Corporation", sector: "Services" },
  { ticker: "SSI", cmpyId: "654", companyName: "SSI Group, Inc.", sector: "Services" },
  { ticker: "STI", cmpyId: "222", companyName: "STI Education Systems Holdings, Inc.", sector: "Services" },
  { ticker: "TBGI", cmpyId: "269", companyName: "Transpacific Broadband Group Int`l. Inc.", sector: "Services" },
  { ticker: "TEL", cmpyId: "6", companyName: "PLDT Inc.", sector: "Services" },
  { ticker: "TUGS", cmpyId: "644", companyName: "Harbor Star Shipping Services, Inc.", sector: "Services" },
  { ticker: "UPSON", cmpyId: "700", companyName: "Upson International Corp.", sector: "Services" },
  { ticker: "WEB", cmpyId: "122", companyName: "PhilWeb Corporation", sector: "Services" },
  { ticker: "WLCON", cmpyId: "665", companyName: "Wilcon Depot, Inc.", sector: "Services" },
  { ticker: "WPI", cmpyId: "173", companyName: "Waterfront Philippines, Incorporated", sector: "Services" },

  // Mining & Oil
  { ticker: "AB", cmpyId: "19", companyName: "Atok-Big Wedge Co., Inc.", sector: "Mining & Oil" },
  { ticker: "APX", cmpyId: "178", companyName: "Apex Mining Co., Inc.", sector: "Mining & Oil" },
  { ticker: "AR", cmpyId: "33", companyName: "Abra Mining and Industrial Corporation", sector: "Mining & Oil" },
  { ticker: "AT", cmpyId: "34", companyName: "Atlas Consolidated Mining and Development Corporation", sector: "Mining & Oil" },
  { ticker: "BC", cmpyId: "108", companyName: "Benguet Corporation", sector: "Mining & Oil" },
  { ticker: "COAL", cmpyId: "637", companyName: "Coal Asia Holdings Incorporated", sector: "Mining & Oil" },
  { ticker: "CPM", cmpyId: "621", companyName: "Century Peak Holdings Corporation", sector: "Mining & Oil" },
  { ticker: "DIZ", cmpyId: "68", companyName: "Dizon Copper-Silver Mines, Inc.", sector: "Mining & Oil" },
  { ticker: "ECVC", cmpyId: "46", companyName: "East Coast Vulcan Mining Corporation", sector: "Mining & Oil" },
  { ticker: "ENEX", cmpyId: "653", companyName: "ENEX Energy Corp.", sector: "Mining & Oil" },
  { ticker: "FNI", cmpyId: "224", companyName: "Global Ferronickel Holdings, Inc.", sector: "Mining & Oil" },
  { ticker: "GEO", cmpyId: "198", companyName: "GEOGRACE Resources Philippines, Inc.", sector: "Mining & Oil" },
  { ticker: "LC", cmpyId: "98", companyName: "Lepanto Consolidated Mining Company", sector: "Mining & Oil" },
  { ticker: "MA", cmpyId: "119", companyName: "Manila Mining Corporation", sector: "Mining & Oil" },
  { ticker: "MARC", cmpyId: "175", companyName: "Marcventures Holdings, Inc.", sector: "Mining & Oil" },
  { ticker: "NI", cmpyId: "103", companyName: "NiHAO Mineral Resources International, Inc.", sector: "Mining & Oil" },
  { ticker: "NIKL", cmpyId: "625", companyName: "Nickel Asia Corporation", sector: "Mining & Oil" },
  { ticker: "OGP", cmpyId: "704", companyName: "OceanaGold (Philippines), Inc.", sector: "Mining & Oil" },
  { ticker: "OPM", cmpyId: "43", companyName: "Oriental Petroleum and Minerals Corporation", sector: "Mining & Oil" },
  { ticker: "ORE", cmpyId: "616", companyName: "Oriental Peninsula Resources Group, Inc.", sector: "Mining & Oil" },
  { ticker: "OV", cmpyId: "45", companyName: "The Philodrill Corporation", sector: "Mining & Oil" },
  { ticker: "PX", cmpyId: "137", companyName: "Philex Mining Corporation", sector: "Mining & Oil" },
  { ticker: "PXP", cmpyId: "628", companyName: "PXP Energy Corporation", sector: "Mining & Oil" },
  { ticker: "UPM", cmpyId: "168", companyName: "United Paragon Mining Corporation", sector: "Mining & Oil" },

  // SME Board
  { ticker: "CTS", cmpyId: "693", companyName: "CTS Global Equity Group, Inc.", sector: "SME Board" },
  { ticker: "HTI", cmpyId: "690", companyName: "Haus Talk, Inc.", sector: "SME Board" },
  { ticker: "IDC", cmpyId: "660", companyName: "Italpinas Development Corporation", sector: "SME Board" },
  { ticker: "KPPI", cmpyId: "672", companyName: "Kepwealth Property Phils., Inc.", sector: "SME Board" },
  { ticker: "LPC", cmpyId: "698", companyName: "LFM Properties Corporation", sector: "SME Board" },
  { ticker: "MFIN", cmpyId: "263", companyName: "Makati Finance Corporation", sector: "SME Board" },
  { ticker: "MM", cmpyId: "677", companyName: "MerryMart Consumer Corp.", sector: "SME Board" },
  { ticker: "X", cmpyId: "656", companyName: "Xurpas Inc.", sector: "SME Board" },
  { ticker: "XG", cmpyId: "705", companyName: "NexGen Energy Corp.", sector: "SME Board" },

  // ETF
  { ticker: "FMETF", cmpyId: "649", companyName: "First Metro Philippine Equity Exchange Traded Fund, Inc.", sector: "ETF" },
];
