CREATE TABLE IF NOT EXISTS "company_financials" (
	"id" serial PRIMARY KEY NOT NULL,
	"ticker" varchar(16) NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL,
	"fiscal_year_ended" varchar(32),
	"currency_unit" varchar(64),
	"current_assets_current" numeric(20, 4),
	"current_assets_previous" numeric(20, 4),
	"total_assets_current" numeric(20, 4),
	"total_assets_previous" numeric(20, 4),
	"current_liabilities_current" numeric(20, 4),
	"current_liabilities_previous" numeric(20, 4),
	"total_liabilities_current" numeric(20, 4),
	"total_liabilities_previous" numeric(20, 4),
	"retained_earnings_current" numeric(20, 4),
	"retained_earnings_previous" numeric(20, 4),
	"stockholders_equity_current" numeric(20, 4),
	"stockholders_equity_previous" numeric(20, 4),
	"stockholders_equity_parent_current" numeric(20, 4),
	"stockholders_equity_parent_previous" numeric(20, 4),
	"book_value_per_share_current" numeric(20, 4),
	"book_value_per_share_previous" numeric(20, 4),
	"gross_revenue_current" numeric(20, 4),
	"gross_revenue_previous" numeric(20, 4),
	"gross_expense_current" numeric(20, 4),
	"gross_expense_previous" numeric(20, 4),
	"income_before_tax_current" numeric(20, 4),
	"income_before_tax_previous" numeric(20, 4),
	"net_income_after_tax_current" numeric(20, 4),
	"net_income_after_tax_previous" numeric(20, 4),
	"net_income_attributable_to_parent_current" numeric(20, 4),
	"net_income_attributable_to_parent_previous" numeric(20, 4),
	"eps_basic_current" numeric(20, 4),
	"eps_basic_previous" numeric(20, 4),
	"eps_diluted_current" numeric(20, 4),
	"eps_diluted_previous" numeric(20, 4),
	CONSTRAINT "company_financials_ticker_unique" UNIQUE("ticker")
);
